spring: 
   datasource: 
       url: jdbc:mysql://127.0.0.1:3306/xingqi_3?useSSL=false&serverTimezone=CST&allowPublicKeyRetrieval=true
       username: xingqi_3
       password: 1234
   jpa: 
      generated-ddl: true
      show-sql: true
   redis: 
      host: 120.78.3.25
      port: 6379
      database: 5